name: 'Hello World Docker'
description: 'Hello'
inputs:
  who-to-greet:
    required: true
    description: 'who to greet'
    default: 'world'

  outputs:
    time:
      description: 'Time we said hello'

  runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
     - ${{ inputs.who-to-greet }}
      
 
